### ISSUE TITLE
3章 net/wasabi/src/http.rs の ToString に関してのエラー

### ISSUE THREAD

**Issue by tkmfujise** [lowlayergirls/wasabi-help#1]
3章ホスト名からIPアドレスへの変換の
net/wasabi/src/http.rs で、
```rs
use alloc::format;
use crate::alloc::string::ToString;
use noli::net::lookup_host;
```
という記述があり、そのまま写経していたのですが、`$ cargo test` をするとエラーが出ます。
```
error[E0433]: failed to resolve: unresolved import
 --> net/wasabi/src/http.rs:4:12
  |
4 | use crate::alloc::string::ToString;
  |            ^^^^^
  |            |
  |            unresolved import
  |            help: a similar path exists: `core::alloc`  

error[E0599]: no method named `to_string` found for reference `&'static str` in the current scope
  --> net/wasabi/src/http.rs:30:69
   |
30 | ...sses".to_string()));
   |          ^^^^^^^^^ method not found in `&str`
```

本家コード ( https://github.com/d0iasm/sababook/blob/main/ch3/saba/net/wasabi/src/http.rs )
のように、`crate::` の部分を消すとエラーが解消できました。
```rs
use alloc::format;
use alloc::string::ToString;
use noli::net::lookup_host;
```

本だと余計な `crate::` がついているように思いましたので報告でした。

**Comment by d0iasm** [comment]
報告ありがとうございます。本とコードの不一致部分に関して、次の版で修正できるかお願いしてみます。ただ、`crate`を消すとエラーが直るという部分は不思議です。

`crate::alloc::string::ToString;` と `alloc::string::ToString;`は実質同じものを指しているはずなので、問題はその部分ではなく、ほかの部分にありそうです。
`extern crate alloc;`とallocに関するモジュールをトップレベルで定義しているので、alloc == crate::alloc となります。

また、net/wasabi/src/http.rsのファイルは、saba_core以下でのテスト時にコンパイルされないはずなので、もしnet/wasabi/src/http.rsにエラーが含まれていても、saba_coreディレクトリでの`cargo test`コマンドには影響がないはずです。
