### ISSUE TITLE
CRLF (`\r\n`) が `\n\r` になっている

### ISSUE THREAD

**Issue by gifnksm** [lowlayergirls/wasabi-help#2]
3章 p.195 で `\r\n` であるべきところが `\n\r` となっています。

本文:

> キャリッジリターンと改行シーケンス（\n\r）

コード例:

> let preprocessed_response = raw_response.trim_start().replace("\n\r", "\n");

出展: 土井 麻未. ［作って学ぶ］ブラウザのしくみ──HTTP、HTML、CSS、JavaScriptの裏側 WEB+DB PRESS plus (p.195). 株式会社技術評論社. Kindle 版.

**Comment by d0iasm** [comment]
ありがとうございます。次の版で修正できるかお願いしてみます。
