### ISSUE TITLE
`HtmlParser#insert_element` メソッドの `set_previous_sibling` をする対象が誤っている

### ISSUE THREAD

**Issue by tnyo43** [lowlayergirls/wasabi-help#3]
4章"要素ノードの追加"（166ページ）の  `HtmlParser#insert_element` の実装について質問です。

本文中で「最後の兄弟ノードを探索して、新しいノードをその直後に挿入します。」と説明している実装が、 `node.previous_sibling <- last_sibling` とするところが `node.previous_sibling <- current.first_child` になっているように思います。[対象のコードはこちらです](https://github.com/d0iasm/sababook/blob/ea7fa7c0b0e64e83aa340457a6b19096726d06ed/ch4/saba/saba_core/src/renderer/html/parser.rs#L126-L131)。

[元の実装だと意図した動作にならないテストを作成した](https://github.com/tnyo43/sample-browser-application/blob/3a60eecbb563660bef692990fe17531c316bb92f/saba_core/src/renderer/html/parser.rs#L601-L654) ので、確認するときに参考になるかなと思います。本書の実装だと、 p 要素の previous_sibling が a 要素ではなく h1 要素になります。
また、 [自分なりに修正を作って](https://github.com/tnyo43/sample-browser-application/blob/3a60eecbb563660bef692990fe17531c316bb92f/saba_core/src/renderer/html/parser.rs#L133-L134)みました。 Rust の実装に不慣れなので正しい実装になってるかわからないですが、最低限動作するようになっています。
また、同様のことは `HtmlParser#insert_char` でも起こってそうです。

5章以降は流し読みした程度ですが、この変更による本書の他の内容への影響はないように思っています。

**Comment by d0iasm** [comment]
issueの報告とテストの作成までありがとうございます！`previous_sibling`に対するテストケースはほとんどなかったはずなので、確かに間違いを見逃していそうです。
内容を確認し、必要であればコードと書籍の修正を行います。

**Comment by d0iasm** [comment]
sabaのディレクトリでコードの修正をしました。
https://github.com/d0iasm/saba/commit/fac3f5e309512ac7f5c1bc41589c7fe951ab663c

おっしゃる通り、`insert_element`メソッドでの`previous_sibling`の設定が間違いでした。
`insert_char`メソッドの方は、今の実装ではcharノードは兄弟ノードを持たないため、`previous_sibling`は何もない状態が正しいです。

改めて報告ありがとうございました。
