### ISSUE TITLE
p.127 「AfterAttributeValueQuotedの実装」の状態の移動について質問

### ISSUE THREAD

**Issue by taro714** [lowlayergirls/wasabi-help#4]
書籍楽しく読ませていただいています！

p.127 「AfterAttributeValueQuotedの実装」について気になる箇所があったので質問させてください。

本文7行目に以下の記載がありますが、
`それ以外のとき、reconsume フラグを true にし BeforeAttributeValue 状態に移動します。`
Htmlの仕様書を参照すると、「BeforeAttribute**Name**状態に移動」が適切？かと思いました。

また、p.128 ソースコード該当箇所についても、
`self.state = State::BeforeAttributeValue;`

以下のようにするのが適切？かと思いました。
`self.state = State::BeforeAttributeName;`

参考：
https://html.spec.whatwg.org/multipage/parsing.html#after-attribute-value-(quoted)-state
`Anything else This is a missing-whitespace-between-attributes parse error. Reconsume in the before attribute name state.`

**Comment by taro714** [comment]
すみません、上記の記載が不十分でしたので補足させてください。
書籍の実装ですと、属性の間に空白が無い場合に、属性の値に他の属性が含まれてしまいます。

▼属性の間に空白が無い場合に返却されるトークン
`Some(StartTag { tag: "p", self_closing: false, attributes: [Attribute { name: "class", value: "Aid='B'" }, Attribute { name: "foo", value: "bar" }] })`

▼属性の間に空白が無い場合のテスト

    #[test]
    fn test_missing_whitespace_between_attributes() {
		// class属性とid属性の間の空白を除去
        let html = "<p class=\"A\"id='B' foo=bar></p>".to_string();
        let mut tokenizer = HtmlTokenizer::new(html);
        let mut attr1 = Attribute::new();
        attr1.add_char('c', true);
        attr1.add_char('l', true);
        attr1.add_char('a', true);
        attr1.add_char('s', true);
        attr1.add_char('s', true);
        attr1.add_char('A', false);

        let mut attr2 = Attribute::new();
        attr2.add_char('i', true);
        attr2.add_char('d', true);
        attr2.add_char('B', false);

        let mut attr3 = Attribute::new();
        attr3.add_char('f', true);
        attr3.add_char('o', true);
        attr3.add_char('o', true);
        attr3.add_char('b', false);
        attr3.add_char('a', false);
        attr3.add_char('r', false);

        let expected = [
            HtmlToken::StartTag {
                tag: "p".to_string(),
                self_closing: false,
                attributes: vec![attr1, attr2, attr3],
            },
            HtmlToken::EndTag {
                tag: "p".to_string(),
            },
        ];
        for e in expected {
            assert_eq!(Some(e), tokenizer.next());
        }
    }

▼BeforeAttributeNameに変更した場合に返却されるトークン
`Some(StartTag { tag: "p", self_closing: false, attributes: [Attribute { name: "class", value: "A" }, Attribute { name: "id", value: "B" }, Attribute { name: "foo", value: "bar" }] })`

**Comment by d0iasm** [comment]
issueの報告ありがとうございます。そしてリンクやテストなど詳細な情報もありがとうございます。
現在少し忙しくてまだ確認できていないのですが、確認次第またこちらのissueを更新します。

**Comment by d0iasm** [comment]
対応が遅くなってしまってすみません。
おっしゃる通り、BeforeAttributeName状態に移動するのが適切でした。
sabaリポジトリのコードを修正しました。https://github.com/d0iasm/saba/commit/29b43505168a2be021509bd25061342a4fd30004

書籍の本文も第3刷以降で修正が反映されるはずです。

属性の間に空白がない場合、「Anything else This is a missing-whitespace-between-attributes parse error.」とあるように、本来はパースエラーなのですが、このケースもパースできるように対応しているみたいですね。本当は正しくないHTMLのコードだけれど、できる限りうまく動くようにしているケースの一つですね。

改めてありがとうございました！
